USE [master]
GO

/****** Object:  Database [EmotIA]    Script Date: 08/04/2026 22:42:31 ******/
CREATE DATABASE [EmotIA]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmotIA', FILENAME = N'D:\Arquivos de Programas\MSSQL15.SQLEXPRESS\MSSQL\DATA\EmotIA.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EmotIA_log', FILENAME = N'D:\Arquivos de Programas\MSSQL15.SQLEXPRESS\MSSQL\DATA\EmotIA_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmotIA].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EmotIA] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EmotIA] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EmotIA] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EmotIA] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EmotIA] SET ARITHABORT OFF 
GO

ALTER DATABASE [EmotIA] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EmotIA] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EmotIA] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EmotIA] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EmotIA] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EmotIA] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EmotIA] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EmotIA] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EmotIA] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EmotIA] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EmotIA] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EmotIA] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EmotIA] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EmotIA] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EmotIA] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EmotIA] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EmotIA] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EmotIA] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EmotIA] SET  MULTI_USER 
GO

ALTER DATABASE [EmotIA] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EmotIA] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EmotIA] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EmotIA] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EmotIA] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EmotIA] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EmotIA] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EmotIA] SET  READ_WRITE 
GO

